# Generated by Django 3.0.1 on 2019-12-23 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cpf',
            fields=[
                ('NUM_CPF', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('NOME', models.CharField(blank=True, max_length=500, null=True)),
                ('DATA_NASCIMENTO', models.CharField(blank=True, max_length=12, null=True)),
                ('IND_SEXO', models.CharField(blank=True, max_length=2, null=True)),
                ('NOME_MAE', models.CharField(blank=True, max_length=500, null=True)),
                ('NUM_TITULO_ELEITOR', models.CharField(blank=True, max_length=12, null=True)),
                ('TIPO_LOGRADOURO', models.CharField(blank=True, max_length=50, null=True)),
                ('DESCR_LOGRADOURO', models.CharField(blank=True, max_length=100, null=True)),
                ('NUM_LOGRADOURO', models.CharField(blank=True, max_length=50, null=True)),
                ('DESCR_COMPLEMENTO_LOGRADOURO', models.CharField(blank=True, max_length=800, null=True)),
                ('NOME_BAIRRO', models.CharField(blank=True, max_length=500, null=True)),
                ('NUM_CEP', models.CharField(blank=True, max_length=50, null=True)),
                ('NOME_MUNICIPIO', models.CharField(blank=True, max_length=200, null=True)),
                ('SIGLA_UF', models.CharField(blank=True, max_length=50, null=True)),
                ('NUM_DDD', models.CharField(blank=True, max_length=50, null=True)),
                ('NUM_TELEFONE', models.CharField(blank=True, max_length=50, null=True)),
                ('NUM_FAX', models.CharField(blank=True, max_length=50, null=True)),
                ('SE_ESTRANGEIRO', models.CharField(blank=True, max_length=2, null=True)),
                ('NOME_PAIS_NACIONALIDADE', models.CharField(blank=True, max_length=500, null=True)),
                ('COD_SITUACAO_CADASTRAL', models.CharField(blank=True, max_length=2, null=True)),
                ('DESCR_SITUACAO_CADASTRAL', models.CharField(blank=True, max_length=50, null=True)),
                ('DATA_SITUACAO_CADASTRAL', models.CharField(blank=True, max_length=12, null=True)),
                ('DATA_INSCRICAO', models.CharField(blank=True, max_length=12, null=True)),
                ('ANO_OBITO', models.CharField(blank=True, max_length=10, null=True)),
                ('ANO_ULTIMA_ENTREGA_DECLARACAO', models.CharField(blank=True, max_length=10, null=True)),
                ('DATA_BASE', models.CharField(blank=True, max_length=12, null=True)),
            ],
        ),
    ]
